/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppDeployRouteImport } from './routes/app.deploy'
import { Route as AppIdentusRouteImport } from './routes/app.identus'
import { Route as AppIpsRouteImport } from './routes/app.ips'
import { Route as AppMidnightRouteImport } from './routes/app.midnight'
import { Route as AppVerifyRouteImport } from './routes/app.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDeployRoute = AppDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentusRoute = AppIdentusRouteImport.update({
  id: '/identus',
  path: '/identus',
  getParentRoute: () => AppRoute,
} as any)
const AppIpsRoute = AppIpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => AppRoute,
} as any)
const AppMidnightRoute = AppMidnightRouteImport.update({
  id: '/midnight',
  path: '/midnight',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/identus': typeof AppIdentusRoute
  '/app/ips': typeof AppIpsRoute
  '/app/midnight': typeof AppMidnightRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/identus': typeof AppIdentusRoute
  '/app/ips': typeof AppIpsRoute
  '/app/midnight': typeof AppMidnightRoute
  '/app/verify': typeof AppVerifyRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/deploy': typeof AppDeployRoute
  '/app/identus': typeof AppIdentusRoute
  '/app/ips': typeof AppIpsRoute
  '/app/midnight': typeof AppMidnightRoute
  '/app/verify': typeof AppVerifyRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/deploy'
    | '/app/identus'
    | '/app/ips'
    | '/app/midnight'
    | '/app/verify'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/deploy'
    | '/app/identus'
    | '/app/ips'
    | '/app/midnight'
    | '/app/verify'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/deploy'
    | '/app/identus'
    | '/app/ips'
    | '/app/midnight'
    | '/app/verify'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deploy': {
      id: '/app/deploy'
      path: '/deploy'
      fullPath: '/app/deploy'
      preLoaderRoute: typeof AppDeployRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identus': {
      id: '/app/identus'
      path: '/identus'
      fullPath: '/app/identus'
      preLoaderRoute: typeof AppIdentusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ips': {
      id: '/app/ips'
      path: '/ips'
      fullPath: '/app/ips'
      preLoaderRoute: typeof AppIpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/midnight': {
      id: '/app/midnight'
      path: '/midnight'
      fullPath: '/app/midnight'
      preLoaderRoute: typeof AppMidnightRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDeployRoute: typeof AppDeployRoute
  AppIdentusRoute: typeof AppIdentusRoute
  AppIpsRoute: typeof AppIpsRoute
  AppMidnightRoute: typeof AppMidnightRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDeployRoute: AppDeployRoute,
  AppIdentusRoute: AppIdentusRoute,
  AppIpsRoute: AppIpsRoute,
  AppMidnightRoute: AppMidnightRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
